services:
  - type: web
    name: inspector-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inspector-db
          property: connectionString
      - key: PORT
        value: 10000

databases:
  - name: inspector-db
    plan: free
